
languageCode = "de-de"
theme = "skeleton"
baseurl = "http://www.blawatt.de/"

author = "Jens Blawatt"
title = "Jens Blawatt.de"
pygmentsuseclasses = true
builddrafts = true

disqusShortname = "blawatt"
googleAnalytics = "U1dAYHC-mS1AjNJ2dYrHnApNxvjQ1VB2f_3wz7AkzvE"

[[menu.main]]
    name = "Blog"
    url = "/blog/"
[[menu.main]]
    name = "Code"
    url = "http://bitbucket.org/jblawatt"
[[menu.main]]
    name = "Ãœber Mich"
    url = "/about/"
    
[params]
Author = "Jens Blawatt"
Email = "jblawatt@googlemail.com"
Twitter = "//twitter.com/jblawatt"
DateForm = "Jan 2, 2006"
DateFormFull = "Mon Jan 2 2006 15:04:05 MST"
Lang = "de"
CacheBuster = true
GitHub = "//github.com/jblawatt"
Bitbucket = "//bitbucket.org/jblawatt"
Xing = "//www.xing.com/profile/Jens_Blawatt2"

Copyright = "Copyright (c) 2016, Jens Blawatt; all rights reserved."

PrismTheme = "okaidia"

ExtraCssFiles = [
    "//raw.githubusercontent.com/PrismJS/prism-themes/master/themes/prism-atom-dark.css"
]

ExtraJsFiles = [
]

[blackfriday]
extensions = ["fencedCodeBlocks", "tables", "footnotes"]